import React from 'react';

const createIcon = (name: string) => {
  const Icon = (props: any) => React.createElement('svg', { 'data-testid': `icon-${name}`, ...props });
  Icon.displayName = name;
  return Icon;
};

export const Search = createIcon('Search');
export const Filter = createIcon('Filter');
export const Plus = createIcon('Plus');
export const User = createIcon('User');
export const Mail = createIcon('Mail');
export const Phone = createIcon('Phone');
export const Calendar = createIcon('Calendar');
export const Trash2 = createIcon('Trash2');
export const ChevronUp = createIcon('ChevronUp');
export const ChevronDown = createIcon('ChevronDown');
export const ChevronLeft = createIcon('ChevronLeft');
export const ChevronRight = createIcon('ChevronRight');
export const Tag = createIcon('Tag');
export const Users = createIcon('Users');
export const UserPlus = createIcon('UserPlus');
export const Briefcase = createIcon('Briefcase');
export const Building2 = createIcon('Building2');
export const Target = createIcon('Target');
export const AlertTriangle = createIcon('AlertTriangle');
export const TrendingUp = createIcon('TrendingUp');
export const Star = createIcon('Star');
export const Upload = createIcon('Upload');
export const Download = createIcon('Download');
export const Edit2 = createIcon('Edit2');
export const XCircle = createIcon('XCircle');
export const ArrowRight = createIcon('ArrowRight');
export const MoreHorizontal = createIcon('MoreHorizontal');
export const Clock = createIcon('Clock');
export const CheckCircle = createIcon('CheckCircle');
export const X = createIcon('X');
export const ArrowLeft = createIcon('ArrowLeft');
export const Save = createIcon('Save');
export const Settings = createIcon('Settings');
export const RefreshCw = createIcon('RefreshCw');
export const AlertCircle = createIcon('AlertCircle');
export const Workflow = createIcon('Workflow');
export const Activity = createIcon('Activity');
export const Eye = createIcon('Eye');
export const Loader2 = createIcon('Loader2');
export const CheckSquare = createIcon('CheckSquare');
export const Square = createIcon('Square');
export const DollarSign = createIcon('DollarSign');
export const BarChart3 = createIcon('BarChart3');
export const BookOpen = createIcon('BookOpen');
export const FileText = createIcon('FileText');
export const Receipt = createIcon('Receipt');
export const Check = createIcon('Check');
export const Printer = createIcon('Printer');
export const Info = createIcon('Info');
export const Pencil = createIcon('Pencil');
export const Percent = createIcon('Percent');
